[project]
name = "todo"
version = "0.1.0"
description = "CSSE6400 Practicals - TODO Application in Python using Flask"
authors = [
    {name = "mitsudz",email = "MittunS2003@gmail.com"}
]
readme = "README.md"
requires-python = "^3.9"
dependencies = [
    "flask (>=3.1.0,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
